### ISSUE TITLE
Spin CW vs CCW

### ISSUE THREAD

**Issue by adipurdila** [zurb/motion-ui#76]
The spin keyframe function seems to generate the same keyframe, no matter what direction I choose for the animation.

So these:

```sass
@include mui-animation(spin(ccw));
@include mui-animation(spin(cw));
```

results in this:

```css
.spin-cw {
  animation-name: spin-cw-1turn; }
@keyframes spin-cw-1turn {
  0% {
    transform: rotate(-1turn); }
  100% {
    transform: rotate(0); } }
.spin-ccw {
  animation-name: spin-cw-1turn; }
@keyframes spin-cw-1turn {
  0% {
    transform: rotate(0); }
  100% {
    transform: rotate(1turn); } }
```

Wouldn't a CCW rotation be like this?

```css
@keyframes spin-ccw-1turn {
  0% {
    transform: rotate(0); }
  100% {
    transform: rotate(-1turn); } }
```
