### ISSUE TITLE
CSS output incomplete for transitions and animations 

### ISSUE THREAD

**Issue by adrienjs** [zurb/motion-ui#93]
Hello,
Foundation 6 works fine on my web hosting but I have a problem with Motion UI.

Example with a transition:
`#logo {
  @include mui-fade (in, $ duration: 4s);
}`

The CSS output is:
`.mui-enter {
  transition-duration: 500ms;
  transition-timing-function: linear;
  transition-duration: 4s;
  opacity: 0;
  transition-property: opacity; }
 .mui-enter.mui-enter-active {
    opacity: 1; }`

ID selector is missing. The CSS output should be:
`#logo.mui-enter {
  transition-duration: 500ms;
  transition-timing-function: linear;
  transition-duration: 4s;
  opacity: 0;
  transition-property: opacity; }
 #logo.mui-enter.mui-enter-active {
    opacity: 1; }`

Example with an animation:
`h1 {
  animation-name: fade-0-to-100;
  animation-duration: 4s;
}`

The CSS output is:
`@keyframes fade-0-to-100 {
       {
        opacity: 0; }
       {
        opacity: 1; } }`

Percentage for first and last keyframes are missing. The CSS output should be:
`@keyframes fade-0-to-100 {
      0% {
        opacity: 0; }
      100% {
        opacity: 1; } }`

Where could the problem come from?
I use scssphp a compiler for SCSS 3.x written in PHP ([http://leafo.github.io/scssphp/]), but I don't think this is the problem because otherwise the generated CSS code is good.

**Comment by ncoden** [comment]
Hi @adrienjs. Sorry for the _very_ late reply.

I am not able to reproduce it. For:
```scss
#logo { @include mui-fade (in, $ duration: 4s); }
```

I have:
```css
#logo.mui-enter {
  transition-duration: 500ms;
  transition-timing-function: linear;
  transition-duration: 4s;
  opacity: 0;
  transition-property: opacity; }

#logo.mui-enter.mui-enter-active {
  opacity: 1; }
```

I'm closing this issue. If you still have the issue, please reopen and give your Sass version.
